### ISSUE TITLE
I want to use only this for my 3dEditor, how can i pulled this out

### ISSUE THREAD

**Issue by qikong333** [ievgennaida/animator#2]
![image](https://user-images.githubusercontent.com/23370805/82168019-2a736500-98f0-11ea-8da3-9864239dd45d.png)

**Comment by ievgennaida** [comment]
animation timeline is another project and located here
https://github.com/ievgennaida/animation-timeline-control/issues/10

This project can be used as an usage example.
To get things you want, you should clone this project and remove all unrelated things.
