### ISSUE TITLE
what is the data format

### ISSUE THREAD

**Issue by qikong333** [ievgennaida/animator#3]
![image](https://user-images.githubusercontent.com/23370805/82183208-23604d00-9918-11ea-888b-85cc97046e22.png)
In fact, I have introduced the component.But I can't find the corresponding data format to generate a graph like yours

![image](https://user-images.githubusercontent.com/23370805/82183403-7b974f00-9918-11ea-8295-3f178d889830.png)

**Comment by ievgennaida** [comment]
This project has nothing to do with the animation timeline, please open issues in the corresponding repositories. 

And there is no "data format", objects should be passed controlled by the interfaces. Interfaces are part of the module. If you are using visual studio code as IDE you will see method signatures  as a popup.
 
````const model = {
    rows: {
        row: {
            keyframes: [ {val: 200} as TimelineKeyframe, {val: 5000} as TimelineKeyframe ] as Array<TimelineKeyframe>
        }
        as TimelineRow
    }
    as Array < TimelineRow >
}
as TimelineModel;```

You can create TypeScript classes and implement corresponding interfaces, or you can just extend existing interfaces if this is required. 


Also, pure JavaScript example is presented here:
https://github.com/ievgennaida/animation-timeline-control/blob/master/index.html

I would recommend you to check TypeScript, JavaScript documentation first.

**Comment by qikong333** [comment]
Thank you, sorry, I will pay attention
